config/routes.rb
SurveyManager::Application.routes.draw do

  resources :question_types

  resources :surveys do
    get 'open' => "surveys#open"
    post 'submit_response' => "surveys#submit_response"
    post 'questions/bulk_update_order' => 'questions#bulk_update_order'
    get 'export_csv' => 'survey_responses#export_csv'
    
    
    resources :survey_responses
    
    resources :questions do
      post 'answer_options/bulk_update_order' => 'answer_options#bulk_update_order'
      resources :answer_options do
      end
    end
  end
  

  root :to => "surveys#index"

end

app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
  # GET /question_types
  # GET /question_types.json
  def index
    @question_types = QuestionType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_types }
    end
  end

  # GET /question_types/1
  # GET /question_types/1.json
  def show
    @question_type = QuestionType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_type }
    end
  end

  # GET /question_types/new
  # GET /question_types/new.json
  def new
    @question_type = QuestionType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_type }
    end
  end

  # GET /question_types/1/edit
  def edit
    @question_type = QuestionType.find(params[:id])
  end

  # POST /question_types
  # POST /question_types.json
  def create
    @question_type = QuestionType.new(params[:question_type])

    respond_to do |format|
      if @question_type.save
        format.html { redirect_to @question_type, notice: 'Question type was successfully created.' }
        format.json { render json: @question_type, status: :created, location: @question_type }
      else
        format.html { render action: "new" }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_types/1
  # PUT /question_types/1.json
  def update
    @question_type = QuestionType.find(params[:id])

    respond_to do |format|
      if @question_type.update_attributes(params[:question_type])
        format.html { redirect_to @question_type, notice: 'Question type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_types/1
  # DELETE /question_types/1.json
  def destroy
    @question_type = QuestionType.find(params[:id])
    @question_type.destroy

    respond_to do |format|
      format.html { redirect_to question_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/views/question_types/_form.html.erb
<%= simple_form_for @question_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :type_name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                question_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/question_types/edit.html.erb
<%- model_class = QuestionType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/question_types/index.html.erb
<%- model_class = QuestionType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:type_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @question_types.each do |question_type| %>
      <tr>
        <td><%= link_to question_type.id, question_type_path(question_type) %></td>
        <td><%= question_type.type_name %></td>
        <td><%=l question_type.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_type_path(question_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_type_path(question_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_type_path,
            :class => 'btn btn-primary' %>

app/views/question_types/new.html.erb
<%- model_class = QuestionType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/question_types/show.html.erb
<%- model_class = QuestionType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:type_name) %>:</strong></dt>
  <dd><%= @question_type.type_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              question_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_type_path(@question_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              question_type_path(@question_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>