config/routes.rb
SurveyManager::Application.routes.draw do

  resources :question_types

  resources :surveys do
    get 'open' => "surveys#open"
    post 'submit_response' => "surveys#submit_response"
    post 'questions/bulk_update_order' => 'questions#bulk_update_order'
    get 'export_csv' => 'survey_responses#export_csv'
    
    
    resources :survey_responses
    
    resources :questions do
      post 'answer_options/bulk_update_order' => 'answer_options#bulk_update_order'
      resources :answer_options do
      end
    end
  end
  

  root :to => "surveys#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :survey_name, :thankyou_text, :intro_text
  has_many :questions
  has_many :survey_responses
  validates_uniqueness_of :survey_name
  validates_presence_of :survey_name
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  skip_before_filter :authorize, :only => [:open, :submit_response]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])
    gon.orderPostPath = survey_questions_bulk_update_order_path(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:survey_id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
  
  def open
    @hide_layout = true
    @survey = Survey.find(params[:survey_id])
    @survey_resp = SurveyResponse.new({ :survey_id => @survey.id })
    respond_to do |format|
      format.html
      format.json {render :partial => 'surveys/open.json'}
    end
  end
  
  def submit_response
    @hide_layout = true
    @survey = Survey.find(params[:survey_id])
    @survey_response = SurveyResponse.new()
    @survey_response.survey_id = @survey.id
    @survey_response.survey_responses = params[:survey_responses]

    respond_to do |format|
      if @survey_response.save
        format.html
        format.json { render json: { 'thankyou_text' => @survey.thankyou_text} , status: :created, location: @survey_response }
      else
        format.html { render action: "open" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= simple_form_for @survey, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :survey_name %>
  <br>
  <label>Introduction Text (optional):</label>
  <%= f.text_area :intro_text, :style=>'width:300px;height:100px' %>
  <br><br>
  <label>Thank You Text (optional):</label>
  <%= f.text_area :thankyou_text, :style=>'width:300px;height:100px' %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                surveys_path, :class => 'btn' %>
  </div>
<% end %>

app/views/surveys/_open.json.erb
{
  "survey": <%= raw(@survey.to_json) %>,
  "target_url": "<%= survey_submit_response_url(@survey)%>",
  "questions": [
    <% @survey.questions.each_with_index do |q,index| %>
      {
        "id": "<%= q.id %>",
        "question_text": "<%= raw q.question_text.gsub("\"", "'") %>",
        "question_type": "<%= raw q.question_type.type_name %>",
        "order_num": "<%= raw q.order_num %>"
        <% if q.question_type.type_name == "Single Option" || q.question_type.type_name == "Multi-Option" %>
          ,"answer_options": [
              <% q.answer_options.each_with_index do |a, index| %>
                {
                  "id": "<%= raw a.id %>",
                  "option_text" : "<%= raw a.option_text.gsub("\"", "'") %>"
                }    
                <% if index < (q.answer_options.count - 1) %>
                  ,
                <% end %>
              <% end %>
            ]
        <% end %>
      }
      <% if index < (@survey.questions.count - 1) %>
        ,
      <% end %>
    <% end %>
    
  ]
}

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:survey_name) %></th>
      <th><%= model_class.human_attribute_name(:created_on) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td>
          <%= survey.id %>
        </td>
        <td><%= survey.survey_name %></td>
        <td><%= survey.created_at.strftime("%B %d, %Y") %></td>
        <td>
          <%= link_to 'Open',
              survey_open_path(survey), :class => 'btn btn-mini btn-primary' %>
          <%= link_to 'View Responses',
                      survey_survey_responses_path(survey), :class => 'btn btn-mini' %>
          <%= link_to 'Export Responses',
                      survey_export_csv_path(survey, 'csv'), :class => 'btn btn-mini' %>
          <% if current_user.email == 'jose@intermediapost.com' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        survey_path(survey), :class => 'btn btn-mini' %>
            <%= link_to t('.rename', :default => t("helpers.links.rename")),
                        edit_survey_path(survey), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        survey_path(survey),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.email == 'jose@intermediapost.com' %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_survey_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/open.html.erb
<%- model_class = Survey -%>

<% content_for :page_js do %>
 
  jQuery(document).ready(function(){
  
      $("#new_survey_response").validate({
        rules: {
        
          <% @survey.questions.each_with_index do |question, index_num| %>

            <% 
              if params[:skip_val] == '1'
                question_required = false
              else
                question_required = question.required_field ? question.required_field : (question.is_email ? "$('##{question.form_field_input_name}[value=\"\"]').length > 0" : false)
              end 
            %>

            "<%= raw(question.form_field_input_name) %>": {
              required: <%= raw(question_required) %>,
              email: <%= question.is_email %>,
              <% if question.confirmation_for_question != nil %>
              equalTo: "#<%= raw(question.confirmation_for_question.form_field_id_name) %>",
              <% end %>
            } <%= question == @survey.questions.last ? '' : ',' %>
          <% end %>
        },
        messages: {
          <% @survey.questions.each_with_index do |question, index_num| %>
            "<%= raw(question.form_field_input_name) %>": {
              required: <%= raw(question.is_email ? "'Email address required'" : "'Field required'") %>,
              <% if question.confirmation_for_question != nil %>
              equalTo: 'Does not match your answer to question #<%= question.confirmation_for_question.order_num+1 %>'
              <% end %>
            }<%= raw(question == @survey.questions.last ? '' : ',') %>
          <% end %>
        }
      });


  });
    
<% end %>

<div class="page-header">
  <h1><%= @survey.survey_name %></h1>
</div>

<% if !@survey.intro_text.blank? %>
  <div>
    <h4>
    <%= @survey.intro_text %>
    </h4>
  </div>
  
  <hr>
<% end %>

<div class="survey_form_wrapper row">
  <div>
    <%= simple_form_for @survey_resp, :url => survey_submit_response_path(@survey), :method => :post do |f| %>
      <ol>
        <%= simple_fields_for :survey_responses do |resp_form| %>
          <% @survey.questions.each_with_index do |question, index_num| %>
            <li value = "<%= index_num+1 %>">
              <label class="inline" for="survey_responses[<%=question.id.to_s%>]"><%= question.question_text %></label>
            </li>
            <li class="unstyled">
              <% if question.question_type.single_option? %>
              
                <ul class="unstyled">
                  <li>
                    <%= resp_form.input question.id.to_s, collection: question.answer_options, as: :radio, label_method: :option_text, value_method: :id, :required => true, :prompt => false, :label => false, :wrapper => :inline_checkbox %>

                  </li>
                </ul>
                
              <% elsif question.question_type.multi_option? %>
              
                <ul class="unstyled">
                  <li>
                    <%= resp_form.input question.id.to_s, collection: question.answer_options, as: :check_boxes, label_method: :option_text, value_method: :id, :required => true, :prompt => false, :label => false, :wrapper => :inline_checkbox %>
                  </li>
                </ul>
                
              
              <% elsif question.question_type.short_text? %>
              
                <%= resp_form.text_field question.id.to_s, :placeholder => 'Enter Answer Here' %>
              
              <% elsif question.question_type.open_ended_text? %>
              
                <%= resp_form.text_area question.id.to_s, :placeholder => 'Enter Answer Here', :rows => 10, :cols => 75 %>
              
              <% end %>
              
              <br><br>
  
            
            </li>
          <% end %>
        <% end %>
      </ol>
      <div class="divider"></div>
        <div class="divider"></div>
      <p>
        <%= f.hidden_field 'kiosk_mode', :value => ((params[:skip_val].nil? || params[:skip_val] == '0') ? 'false' : 'true') %>
        <%= f.button :submit, :class => 'btn-primary', :value => "Submit" %>
      </p>
    <% end %>
  </div>
</div>

app/views/surveys/show.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:survey_name) %>:</strong></dt>
  <dd><%= @survey.survey_name %><br><br></dd>
  <dt><strong><%= model_class.human_attribute_name(:intro_text) %>:</strong></dt>
  <dd><%= @survey.intro_text %><br><br></dd>
  <dt><strong><%= model_class.human_attribute_name(:thank_you_text) %>:</strong></dt>
  <dd><%= @survey.thankyou_text %></dd>
</dl>

<h3>Questions:</h3>

<input type='button' id='reorder_btn' value="Reorder Items" class="btn btn-secondary" autocomplete="off" />
<br>
<br>

<table class="table table-striped items-table">
  <tr>
    <th width="150px">Type</th>
    <th width="50px">#</th>
    <th>Text</th>
    <th width="150px"></th>
  </tr>
  <% @survey.questions.each do |question| %>
    <tr>
      <td><%= question.question_type.type_name %></td>
      <td><%= question.order_num + 1 %></td>
      <td><%= truncate(question.question_text, :length => 200, :separator => " ") %></td>
      <td>
          <%= link_to t('.view', :default => t("helpers.links.view")),
              survey_question_path(params[:id],question), :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_survey_question_path(params[:id],question), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      survey_question_path(params[:id],question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        
      </td>
    </tr>
  <% end %>
</table>

<ul class="sortable inline-block">
  <% @survey.questions.each do |question| %>
    <li class="icon-resize-vertical listing-item" id="<%= question.id %>">&nbsp;&nbsp;<%= question.order_num + 1 %> - <%= question.question_text %><br></li>
  <% end %>
</ul>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
      surveys_path, :class => 'btn' %>
  &nbsp;&nbsp;
  | 
  &nbsp;&nbsp;
  <%= link_to t('.add_question', :default => t("helpers.links.add_question")),
              new_survey_question_path(params[:id]), :class => 'btn btn-primary'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_survey_path(@survey), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              survey_path(@survey),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/surveys/submit_response.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%= @survey.survey_name %></h1>
</div>

<% if !@survey.thankyou_text.blank? %>


  <%# if(params[:survey_response][:kiosk_mode] == 'true') %>
    <script type="text/javascript">
      alert("<%= @survey.thankyou_text %>");
      window.location = ('/surveys/<%= @survey.id %>/open?skip_val=<%= (params[:survey_response][:kiosk_mode] == 'true' ? '1' : '0')%>')
    </script>
    
  
  <%# else %>
  <!--
    <div>
      <h4>
      <%= @survey.thankyou_text %>
      </h4>
    </div>
    -->
  <%# end %>
<% end %>