config/routes.rb
SurveyManager::Application.routes.draw do

  resources :question_types

  resources :surveys do
    get 'open' => "surveys#open"
    post 'submit_response' => "surveys#submit_response"
    post 'questions/bulk_update_order' => 'questions#bulk_update_order'
    get 'export_csv' => 'survey_responses#export_csv'
    
    
    resources :survey_responses
    
    resources :questions do
      post 'answer_options/bulk_update_order' => 'answer_options#bulk_update_order'
      resources :answer_options do
      end
    end
  end
  

  root :to => "surveys#index"

end

app/models/answer_option.rb
class AnswerOption < ActiveRecord::Base
  belongs_to :question
  attr_accessible :option_text, :question_id, :order_num
  
  default_scope :order => :order_num
end

app/controllers/answer_options_controller.rb
class AnswerOptionsController < ApplicationController
  # GET /answer_options
  # GET /answer_options.json
  def index
    @answer_options = AnswerOption.order(:order_num).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answer_options }
    end
  end

  # GET /answer_options/1
  # GET /answer_options/1.json
  def show
    @answer_option = AnswerOption.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer_option }
    end
  end

  # GET /answer_options/new
  # GET /answer_options/new.json
  def new
    @answer_option = AnswerOption.new

    @question = Question.find(params[:question_id])
    @survey = Survey.find(params[:survey_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer_option }
    end
  end

  # GET /answer_options/1/edit
  def edit
    @answer_option = AnswerOption.find(params[:id])
    @question = Question.find(params[:question_id])
    @survey = Survey.find(params[:survey_id])
  end

  # POST /answer_options
  # POST /answer_options.json
  def create
    @answer_option = AnswerOption.new(params[:answer_option])

    respond_to do |format|
      if @answer_option.save
        format.html { redirect_to survey_question_path(@answer_option.question.survey, @answer_option.question), notice: 'Answer option was successfully created.' }
        format.json { render json: @answer_option, status: :created, location: @answer_option }
      else
        format.html { render action: "new" }
        format.json { render json: @answer_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answer_options/1
  # PUT /answer_options/1.json
  def update
    @answer_option = AnswerOption.find(params[:id])

    respond_to do |format|
      if @answer_option.update_attributes(params[:answer_option])
        format.html { redirect_to survey_question_path(@answer_option.question.survey, @answer_option.question), notice: 'Answer option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer_option.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def bulk_update_order
    
    option = nil
    failed = false
    
    params[:items].each_with_index do |item,index|      
      option = AnswerOption.find(item)
      option.order_num = index
      option.save!
    end

    params[:items].each_with_index do |item,index|
      option = AnswerOption.find(item)
      if option.order_num != index + 1
        failed = true
      end
    end

    if failed == false
      render :json => {:result => :success}
    else
      render :json => {:result => :failed}
    end
  end

  # DELETE /answer_options/1
  # DELETE /answer_options/1.json
  def destroy
    @answer_option = AnswerOption.find(params[:id])
    @answer_option.destroy

    respond_to do |format|
      format.html { redirect_to answer_options_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answer_options_helper.rb
module AnswerOptionsHelper
end

app/views/answer_options/_form.html.erb
<%= simple_form_for [@survey, @question, @answer_option], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :option_text %>
  <%= f.hidden_field :question_id, :value => params[:question_id] %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                survey_question_path(@survey.id, @question.id), :class => 'btn' %>
  </div>
<% end %>

app/views/answer_options/edit.html.erb
<%- model_class = AnswerOption -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answer_options/index.html.erb
<%- model_class = AnswerOption -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:option_text) %></th>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answer_options.each do |answer_option| %>
      <tr>
        <td><%= link_to answer_option.id, answer_option_path(answer_option) %></td>
        <td><%= answer_option.option_text %></td>
        <td><%= answer_option.question_id %></td>
        <td><%=l answer_option.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_option_path(answer_option), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_option_path(answer_option),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_option_path,
            :class => 'btn btn-primary' %>

app/views/answer_options/new.html.erb
<%- model_class = AnswerOption -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answer_options/show.html.erb
<%- model_class = AnswerOption -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:option_text) %>:</strong></dt>
  <dd><%= @answer_option.option_text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question_id) %>:</strong></dt>
  <dd><%= @answer_option.question_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answer_options_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_option_path(@answer_option), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_option_path(@answer_option),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>