config/routes.rb
SurveyManager::Application.routes.draw do

  resources :question_types

  resources :surveys do
    get 'open' => "surveys#open"
    post 'submit_response' => "surveys#submit_response"
    post 'questions/bulk_update_order' => 'questions#bulk_update_order'
    get 'export_csv' => 'survey_responses#export_csv'
    
    
    resources :survey_responses
    
    resources :questions do
      post 'answer_options/bulk_update_order' => 'answer_options#bulk_update_order'
      resources :answer_options do
      end
    end
  end
  

  root :to => "surveys#index"

end

app/controllers/survey_responses_controller.rb
class SurveyResponsesController < ApplicationController
  # GET /survey_responses
  # GET /survey_responses.json
  def index
    @survey = Survey.find(params[:survey_id])
    @survey_responses = @survey.survey_responses.all
    @random_sample = @survey_responses.nil? ? nil : @survey_responses.sample(random:1)
    convert_responses(@survey_responses)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @survey_responses }
    end
  end
  
  def export_csv
    @survey = Survey.find(params[:survey_id])
    @survey_responses = @survey.survey_responses.all
    
    convert_responses(@survey_responses)
    @questions = @survey.questions
    @field_values = extract_field_values_from_responses([params[:question_id]])
    @field_values.each do |respondent|
      respondent.each do |response|
        if(response.is_a? Array)
          response = response.join(",")
        end
      end
    end
    
  end

  # GET /survey_responses/1
  # GET /survey_responses/1.json
  def show
    @survey_response = SurveyResponse.find(params[:id])
    
    convert_responses([@survey_response])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey_response }
    end
  end

  # GET /survey_responses/new
  # GET /survey_responses/new.json
  def new
    @survey_response = SurveyResponse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey_response }
    end
  end

  # GET /survey_responses/1/edit
  def edit
    @survey_response = SurveyResponse.find(params[:id])
  end

  # POST /survey_responses
  # POST /survey_responses.json
  def create
    @survey_response = SurveyResponse.new(params[:survey_response])

    respond_to do |format|
      if @survey_response.save
        format.html { redirect_to survey_survey_responses_path(params[:survey_id]), notice: 'Survey response was successfully created.' }
        format.json { render json: @survey_response, status: :created, location: @survey_response }
      else
        format.html { render action: "new" }
        format.json { render json: @survey_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /survey_responses/1
  # PUT /survey_responses/1.json
  def update
    @survey_response = SurveyResponse.find(params[:id])

    respond_to do |format|
      if @survey_response.update_attributes(params[:survey_response])
        format.html { redirect_to survey_survey_responses_path(params[:survey_id]), notice: 'Survey response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_responses/1
  # DELETE /survey_responses/1.json
  def destroy
    @survey_response = SurveyResponse.find(params[:id])
    @survey_response.destroy

    respond_to do |format|
      format.html { redirect_to survey_survey_responses_path(params[:survey_id]) }
      format.json { head :no_content }
    end
  end
  
  def convert_responses(survey_responses)
    @responses = []
    x = 0

    survey_responses.each do |survey_response|

      x += 1
      
      # FINAL FORMAT = @responses[index of survey response submission][index of response to question][index of either question (0) or answer(1)]
      
      @responses[x] = []

      survey_response.survey.questions.each do |q|
          @responses[x].push([q,nil])
      end
      
      survey_response.survey_responses.each do |question,response|
  
          @responses[x].each do |resp|
              if(resp[0].id == question.to_i)
              
                  if (resp[0].question_type.single_option? && response.to_i > 0)
                    resp[1] = AnswerOption.find(response.to_i)
                  else
                    
                      if(resp[0].question_type.multi_option?)
                          options = response[1..response.length-2].split(',')
                          translated_options = options.map{ |x| AnswerOption.find(x.gsub(' ','').gsub('"','').to_i) unless x.gsub(' ','').gsub('"','').to_i == 0 }.compact
                          resp[1] = translated_options
                      else
                          resp[1] =  response
                      end

                  end

              end
          
              @responses[x] = @responses[x].sort_by{ |r| r[0].order_num.nil? ? 0 : r[0].order_num}  
          end

      end
    
      @responses.each do |r|
        if r.nil?
          @responses.delete r
        end
      end
    end
  end
  
  def extract_field_values_from_responses(question_ids)
    question_responses = []
      
    @responses.each do |respondent|
      field_values = []
      respondent.each do |resp|
        
        val = ""
        
        if(resp[1] != nil)
          if(resp[1].is_a? Array)
            resp[1].each do |option|
              if option != resp[1].last
                val = "#{val}#{option.option_text},"
              else
                val = "#{val}#{option.option_text}"
              end
            end
          elsif resp[1].is_a? AnswerOption
            val = resp[1].option_text
          elsif resp[1].is_a? String || resp[1].to_i != 0
            val = resp[1]
          end            
          
          field_values << val

        else
          field_values << ""
        end
      end
      if(field_values.count > 0)
        question_responses << field_values
      end
    end

    
    return question_responses
  end
  
  def extract_questions_from_responses(question_ids)
    questions = []
      
    @responses.last.each do |resp|
      val = ""
      if(resp[0] != nil)
        val = resp[0].question_text
      end        
      questions << val
    end

    
    return questions
  end
end

app/helpers/survey_responses_helper.rb
module SurveyResponsesHelper
end

app/views/survey_responses/_form.html.erb
<%= form_for(@survey_response) do |f| %>
  <% if @survey_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_response.errors.count, "error") %> prohibited this survey_response from being saved:</h2>

      <ul>
      <% @survey_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey %><br />
    <%= f.text_field :survey %>
  </div>
  <div class="field">
    <%= f.label :survey_responses %><br />
    <%= f.text_field :survey_responses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/survey_responses/edit.html.erb
<h1>Editing survey_response</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey_response %> |
<%= link_to 'Back', survey_responses_path %>

app/views/survey_responses/export_csv.csv.erb
<% @questions.each do |question| %><%if question != @questions.last%>"<%=raw(question.question_text.gsub("\"","'"))%>",<% else %>"<%=raw(question.question_text.gsub("\"","'"))%>"<% end %><% end -%>
<% @field_values.each do |responses| -%><% responses.each_with_index do |val, index| -%><% if index < responses.count-1 -%>"<%= raw(val.gsub("\n\r",",").gsub("\r",",").gsub("\"","'")) -%>",<% else -%>"<%= raw(val.gsub("\n\r",",").gsub("\r",",").gsub("\"","'")) -%>"
<% end -%><% end -%><% end -%>

app/views/survey_responses/index.html.erb
<h1>
  <%= @survey.survey_name %>
</h1>

<h3>Survey Responses</h3>

<% if !@random_sample.nil? %>
  <%= link_to "Select Random Response", survey_survey_response_url(@survey,@random_sample), :class => "btn btn-primary" %>
<% end %>
<br><br>

<% @survey_responses.each_with_index do |survey_response, index| %>
  <table class="table table-striped table-bordered">
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="4" style="text-align:right;"></th>
    </tr>

    <% @responses[index].each do |response| %>
      <tr>
        <td><%= response[0].question_text %></td>
        <td colspan="4">
          <% if response[1].is_a? String %>
            <%= response[1] %>
          <% elsif response[0].question_type.single_option? %>
            <%= response[1].option_text %>
          <% elsif response[0].question_type.multi_option? && (response[1].is_a? Array) %>
            <% response[1].each do |option| %>
              <%= option.option_text %>
              <% if option != response[1].last %>
                <br>
              <% end %>
            <% end %>
          <% elsif response[1].is_a? AnswerOption %>
            <%= response[1].option_text %>
          <% elsif response[1].to_i != 0 %>
            <%= response[1] %>
          <% end %>
        </td>
      </tr>
    <% end %>
   
  </table>
  <p align="right">
    <%= link_to 'Show', survey_survey_response_path(params[:survey_id],survey_response) %> 
    <%#= link_to 'Edit', edit_survey_survey_response_path(@survey,survey_response) %>
    <% if current_user.email == 'jose@intermediapost.com' %>
    | 
      <%= link_to 'Destroy', survey_survey_response_path(@survey, survey_response), method: :delete, data: { confirm: 'Are you sure?' } %></th>
    <% end %>
  </p>
  <hr>
<% end %>


<br />

app/views/survey_responses/new.html.erb
<h1>New survey_response</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_responses_path %>

app/views/survey_responses/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @survey_response.survey.survey_name %></h1>

<br><br>

  <table class="table table-striped table-bordered">
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="4" style="text-align:right;"></th>
    </tr>

    <% @responses[0].each do |response| %>
      <tr>
        <td><%= response[0].question_text %></td>
        <td colspan="4">
          <% if response[1].is_a? String %>
            <%= response[1] %>
          <% elsif response[0].question_type.single_option? %>
            <%= response[1].option_text %>
          <% elsif response[0].question_type.multi_option? && (response[1].is_a? Array) %>
            <% response[1].each do |option| %>
              <%= option.option_text %>
              <% if option != response[1].last %>
                <br>
              <% end %>
            <% end %>
          <% elsif response[1].is_a? AnswerOption %>
            <%= response[1].option_text %>
          <% elsif response[1].to_i != 0 %>
            <%= response[1] %>
          <% end %>
        </td>
      </tr>
    <% end %>
   
  </table>

<%= link_to 'Back', survey_survey_responses_path(params[:survey_id]) %>